tide:
  merge_method:
    VaniHaripriya/data-science-pipelines: squash
  
  queries:
  - repos:
    - VaniHaripriya/data-science-pipelines
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    milestone: ""
    reviewApprovedRequired: true

  context_options:    
    from-branch-protection: true    
    skip-unknown-contexts: true
    orgs:
      VaniHaripriya:
        required-contexts:
        - "KFP Manifests"
        repos:
          VaniHaripriya/data-science-pipelines:
            required-contexts:
            - "KFP Manifests"
            branches:
              upstream-kubeflow-pipelines-master: # Specify the branch if needed or omit for default
                from-branch-protection: false
                required-contexts:
                - "KFP Manifests"
                # Optionally define additional contexts if needed
                optional-contexts:
                - "optional_test"
                required-if-present-contexts:
                - "conditional_test"