apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow 

resources:
  - cache-cert-issuer.yaml
  - cache-cert.yaml
  - cache-webhook-config.yaml
  - webhook/pipelineversion-cert-issuer.yaml
  - webhook/pipelineversion-cert.yaml
  - webhook/validating-pipelineversion.yaml
commonLabels:
  app: cache-server-cert-manager

configurations:
- params.yaml
