# This workflow aggregates the status of multiple CI workflows associated with a pull request (PR).
# It is triggered when any of the specified workflows complete.
# The workflow checks the status of all relevant CI workflows, and if they have all succeeded,
# it adds a 'ci-passed' label to the PR.
# If any workflow has failed or was skipped, the 'ci-passed' label is not added.
# You can modify the list of workflows in this file to match the relevant workflows in your CI pipeline.

name: CI Status Aggregation

on:
  workflow_run:
    workflows: ["KFP Manifests"]
    types:
      - completed

jobs:
  check_ci_status:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Set PR_NUMBER
        id: set-vars
        run: |
          PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' < $GITHUB_EVENT_PATH)

          # Print PR_NUMBER
          echo "PR_NUMBER=$PR_NUMBER"

          # Check if PR_NUMBER is valid
          if [ -z "$PR_NUMBER" ]; then
            echo "Pull Request number could not be determined. Exiting."
            exit 1
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Check Status of All Workflows
        run: |
          pr_number=${{ env.PR_NUMBER }}
          echo "Checking statuses for PR #$pr_number"
      
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workflow: KFP Manifests"
          
          # Get the list of workflow runs
          workflow_runs=$(gh run list --workflow "KFP Manifests" --json number,headSha,status --repo $GITHUB_REPOSITORY)

          # Extract the SHA of the PR
          pr_sha=$(gh pr view $pr_number --json headRefOid -q .headRefOid --repo $GITHUB_REPOSITORY)   

          # Print the SHA for debugging
          echo "PR SHA: $pr_sha"

          # Filter the workflow run for the specific PR SHA and print it
          echo "Workflow Run Matching PR SHA:"
          echo "$workflow_runs" | jq --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha)'      

          # Filter the workflow runs for the specific PR SHA
          statuses=$(echo "$workflow_runs" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .status')

          # Print statuses
          echo "Statuses: $statuses"

          # Check if any status is not 'success'
          if echo "$statuses" | grep -qv "completed"; then
            echo "Not all workflows succeeded or were skipped."
            exit 1
          else
            echo "All workflows succeeded. Adding 'ci-passed' label."
            gh pr edit $pr_number --add-label "ci-passed" --repo $GITHUB_REPOSITORY
          fi
    env:
     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}