# This workflow aggregates the status of multiple CI workflows associated with a pull request (PR).
# It is triggered when any of the specified workflows complete.
# The workflow checks the status of all relevant CI workflows, and if they have all succeeded,
# it adds a 'ci-passed' label to the PR.
# If any workflow has failed or was skipped, the 'ci-passed' label is not added.
# You can modify the list of workflows in this file to match the relevant workflows in your CI pipeline.

name: CI Status Aggregation

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_ci_status:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_NUMBER and PR_SHA
        id: set-vars
        run: |
          PR_NUMBER=${{ github.event.number }}
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          
          PR_SHA=$(gh pr view $PR_NUMBER --json headRefOid -q .headRefOid --repo $GITHUB_REPOSITORY)
          echo "PR_SHA=$PR_SHA" >> $GITHUB_ENV

      - name: Identify Triggered Workflows
        id: identify-triggered
        run: |
          pr_sha=${{ env.PR_SHA }}
          
          workflow_runs=$(gh run list --json name,conclusion,headSha,status --repo $GITHUB_REPOSITORY)
          filtered_workflows=$(echo "$workflow_runs" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | select(.status != "skipped") | .name' | grep -v '^CI Status Aggregation$')

          if [ -z "$filtered_workflows" ]; then
            echo "No workflows were triggered for this PR. Exiting."
            exit 0
          fi

          filtered_workflows_string=$(echo "$filtered_workflows" | tr '\n' ',' | sed 's/,$//')
          echo "TRIGGERED_WORKFLOWS=$filtered_workflows_string" >> $GITHUB_ENV

      - name: Wait for All Triggered Workflows to Complete
        run: |
          pr_sha=${{ env.PR_SHA }}
          all_completed=false
          failure_reasons=""

          while [ "$all_completed" = false ]; do
            all_completed=true
            IFS=',' read -ra workflows <<< "${{ env.TRIGGERED_WORKFLOWS }}"
            for workflow in "${workflows[@]}"; do
              raw_response=$(gh run list --workflow "$workflow" --json status,conclusion,headSha --repo $GITHUB_REPOSITORY)

              status=$(echo "$raw_response" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .status' | head -n 1)
              conclusion=$(echo "$raw_response" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .conclusion' | head -n 1)               
              
              if [ -z "$status" ]; then
                echo "No matching workflow run found for PR SHA: $pr_sha. Exiting..."
                exit 1
              fi

              if [ "$status" != "completed" ]; then
                all_completed=false
                break
              elif [ "$conclusion" != "success" ]; then
                all_completed=false
                failure_reasons+="$workflow failed"
                echo -e "Some workflows failed:\n$failure_reasons"   
                exit 1             
              fi
            done

            if [ "$all_completed" = false ]; then
              sleep 30
            fi
          done

          echo "All triggered workflows have completed."        

      - name: Check Status of All Completed Workflows
        run: |
          pr_sha=${{ env.PR_SHA }}
          all_succeeded=true
          
          IFS=',' read -ra workflows <<< "${{ env.TRIGGERED_WORKFLOWS }}"
          for workflow in "${workflows[@]}"; do
            conclusion=$(gh run list --workflow "$workflow" --json conclusion --repo $GITHUB_REPOSITORY | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .conclusion')
            
            if [ "$conclusion" != "success" ]; then
              all_succeeded=false
            fi
          done

          if [ "$all_succeeded" = true ]; then
            gh pr edit ${{ github.event.number }} --add-label "ci-passed" --repo $GITHUB_REPOSITORY
          else
            exit 1
          fi