# This workflow aggregates the status of multiple CI workflows associated with a pull request (PR).
# It is triggered every 10 minutes and checks the status of all relevant CI workflows.
# If all workflows have completed and succeeded, it adds a 'ci-passed' label to the PR.
# If any workflow is still running, the workflow exits and will check again on the next scheduled run.
# If any workflow has failed, the 'ci-passed' label is not added, and the workflow exits with an error.

name: CI Status Aggregation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_ci_status:
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_NUMBER and PR_SHA
        id: set-vars
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Scheduled run, finding latest open PR."
            PR_NUMBER=$(gh pr list --state open --json number --jq '.[0].number' --repo $GITHUB_REPOSITORY)
          else
            PR_NUMBER=${{ github.event.number }}
          fi

          if [ -z "$PR_NUMBER" ]; then
            echo "No open pull request found. Exiting."
            exit 0
          fi

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

          PR_SHA=$(gh pr view $PR_NUMBER --json headRefOid -q .headRefOid --repo $GITHUB_REPOSITORY)
          echo "PR_SHA=$PR_SHA" >> $GITHUB_ENV

      - name: Identify Triggered Workflows
        id: identify-triggered
        run: |
          pr_sha=${{ env.PR_SHA }}
          
          workflow_runs=$(gh run list --json name,conclusion,headSha,status --repo $GITHUB_REPOSITORY)
          filtered_workflows=$(echo "$workflow_runs" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | select(.status != "skipped") | .name' | grep -v '^CI Status Aggregation$')

          if [ -z "$filtered_workflows" ]; then
            echo "No workflows were triggered for this PR. Exiting."
            exit 0
          fi

          filtered_workflows_string=$(echo "$filtered_workflows" | tr '\n' ',' | sed 's/,$//')
          echo "TRIGGERED_WORKFLOWS=$filtered_workflows_string" >> $GITHUB_ENV

      - name: Check Status and Conclusion of Triggered Workflows
        run: |
          pr_sha=${{ env.PR_SHA }}
          all_succeeded=true

          IFS=',' read -ra workflows <<< "${{ env.TRIGGERED_WORKFLOWS }}"
          for workflow in "${workflows[@]}"; do
            raw_response=$(gh run list --workflow "$workflow" --json status,conclusion,headSha --repo $GITHUB_REPOSITORY)

            status=$(echo "$raw_response" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .status' | head -n 1)
            conclusion=$(echo "$raw_response" | jq -r --arg pr_sha "$pr_sha" '.[] | select(.headSha == $pr_sha) | .conclusion' | head -n 1)

            if [ -z "$status" ]; then
              echo "No matching workflow run found for workflow: $workflow. Exiting..."
              exit 1
            fi

            if [ "$status" != "completed" ]; then
              echo "$workflow is still in progress. Exiting to check again in the next scheduled run."
              exit 0
            fi

            if [ "$conclusion" != "success" ]; then
              echo "$workflow failed. Exiting."
              exit 1
            fi
          done

          echo "All triggered workflows have completed successfully."

      - name: Add 'ci-passed' Label to PR
        run: |
          gh pr edit ${{ env.PR_NUMBER }} --add-label "ci-passed" --repo $GITHUB_REPOSITORY