name: KFP Manifests

on:
  push:
    branches: [master]
  pull_request: # Remove paths filtering
    branches:
      - master

jobs:
  kubeflow-pipelines-manifests:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    

      - name: Run tests
        if: |
          github.event_name == 'push' || 
          (
            github.event_name == 'pull_request' &&
            (
              contains(github.event.head_commit.message, '.github/workflows/kubeflow-pipelines-manifests.yml') ||
              contains(github.event.head_commit.message, 'manifests/kustomize/')
            )
          )
        run: ./manifests/kustomize/hack/presubmit.sh 
