# This workflow adds the 'ci-passed' label to a pull request once the 'CI Check' workflow completes successfully.

name: Labeling Workflow

on:
  workflow_run:
    workflows: ["CI Check"]
    types:
      - completed

permissions:
  pull-requests: write
  checks: read

jobs:
  add_ci_passed_label:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest    
    steps:
      - name: Add 'ci-passed' label
        run: |
          gh pr edit ${{ env.PR_NUMBER }} --add-label "ci-passed" --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  reset_ci_passed_label:
    if: github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.pull_requests[0].action == 'synchronize' || github.event.workflow_run.pull_requests[0].action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Reset ci-passed label status on PR Synchronization
        run: |
          echo "Resetting 'ci-passed' label as new changes have been pushed."
          gh pr edit ${{ env.PR_NUMBER }} --remove-label "ci-passed" --repo $GITHUB_REPOSITORY || echo "Label not present"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}